In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/vehicle_registration_transactions.csv")
df.head()

,Transaction Month and Year,Make,Model,Model Year,Vehicle Color,Vehicle Type,Vehicle Primary Use,Fuel Type Primary,Fuel Type Secondary,Gross Vehicle Weight Rating Class,...,Plate Background,Plate Configuration,Owner Type,County,State,Postal Code,Transaction Type,Transaction Channel,2020 GEOID,Transaction Count
0,01/01/2020,ACURA,CL,1999,WHITE,PASSENGER CAR,Passenger,Gasoline,NaN,1C,...,Standard Plate,Standard,Individual Owner,King,WA,98117,Registration Renewal,Online,5.303300e+10,1
1,01/01/2020,ACURA,ILX,2013,GRAY,PASSENGER CAR,Passenger,Gasoline,NaN,1B,...,Standard Plate,Standard,Individual Owner,Spokane,WA,99223,Registration Renewal,Online,5.306300e+10,1
2,01/01/2020,ACURA,ILX,2017,BLACK,PASSENGER CAR,Passenger,Gasoline,NaN,1C,...,Standard Plate,Standard,Individual Owner,King,WA,98136,Registration Renewal,Online,5.303301e+10,1
3,01/01/2020,ACURA,ILX,2018,NaN,PASSENGER CAR,Passenger,Gasoline,NaN,1C,...,Standard Plate,Standard,Individual Owner,King,WA,98136,Registration Renewal,Online,5.303301e+10,1
4,01/01/2020,ACURA,ILX,2019,NaN,PASSENGER CAR,Passenger,Gasoline,NaN,1C,...,Standard Plate,Standard,Individual Owner,Thurston,WA,98506,Registration Renewal,Online,5.306701e+10,1

In [3]:
df['Fuel Type Primary'].value_counts()

Gasoline                                    24721935
Diesel                                       1160388
Flexible Fuel Vehicle (FFV)                   835313
Electric                                      471888
Ethanol (E85)                                  10567
Liquefied Petroleum Gas (propane or LPG)         739
Compressed Natural Gas (CNG)                     536
Not Applicable                                   398
Hybrid                                           390
Other                                            245
Steam                                             14
Natural Gas                                        4
Butane                                             3
Hydrogen Fuel Cell                                 3
Name: Fuel Type Primary, dtype: int64

In [9]:
df['Year'] = pd.to_datetime(df['Transaction Month and Year']).dt.year

In [16]:
df.isna().sum()

Transaction Month and Year                        0
Make                                              0
Model                                             0
Model Year                                        0
Vehicle Color                              10803818
Vehicle Type                                      0
Vehicle Primary Use                               0
Fuel Type Primary                                 0
Fuel Type Secondary                        25188369
Gross Vehicle Weight Rating Class           8030241
Gross Vehicle Weight Rating Range (lbs)     8030241
Electrification Level                             0
Plate Background                                  0
Plate Configuration                               0
Owner Type                                        0
County                                            0
State                                             0
Postal Code                                       0
Transaction Type                                  0
Transaction Channel                               0
2020 GEOID                                     3212
Transaction Count                                 0
Year                                              0
dtype: int64

In [17]:
df['Is Electric'] = df['Fuel Type Primary'].apply(lambda x: x == 'Electric')
df['Is Second Electric'] = df['Fuel Type Secondary'].apply(lambda x: x == 'Electric')

In [19]:
df[df['Is Electric'] | df['Is Second Electric']]

,Transaction Month and Year,Make,Model,Model Year,Vehicle Color,Vehicle Type,Vehicle Primary Use,Fuel Type Primary,Fuel Type Secondary,Gross Vehicle Weight Rating Class,...,County,State,Postal Code,Transaction Type,Transaction Channel,2020 GEOID,Transaction Count,Year,Is Electric,Is Second Electric
96,01/01/2020,AUDI,A3,2016,NaN,PASSENGER CAR,Passenger,Electric,Gasoline,NaN,...,King,WA,98052,Registration Renewal,Online,5.303303e+10,1,2020,True,False
97,01/01/2020,AUDI,A3,2016,BLACK,PASSENGER CAR,Passenger,Electric,Gasoline,NaN,...,Kitsap,WA,98110,Registration Renewal,Online,5.303509e+10,1,2020,True,False
98,01/01/2020,AUDI,A3,2018,NaN,PASSENGER CAR,Passenger,Electric,Gasoline,NaN,...,King,WA,98107,Registration Renewal,Online,5.303300e+10,1,2020,True,False
418,01/01/2020,CHEVROLET,AVALANCHE,2006,BLUE,MULTIPURPOSE PASSENGER VEHICLE (MPV),Truck,Gasoline,Electric,2E,...,Spokane,WA,99202,Registration Renewal,In-person,5.306300e+10,1,2020,False,True
419,01/01/2020,CHEVROLET,AVALANCHE,2006,GRAY,MULTIPURPOSE PASSENGER VEHICLE (MPV),Truck,Gasoline,Electric,2E,...,King,WA,98008,Registration Renewal,Online,5.303302e+10,1,2020,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27202339,02/01/2024,VOLKSWAGEN,E-GOLF,2015,ALUMINUM / SILVER,PASSENGER CAR,Passenger,Electric,NaN,1,...,King,WA,98177,Registration Renewal,Mail-in,5.303302e+10,1,2024,True,False
27202345,02/01/2024,VOLKSWAGEN,ID.4,2023,NaN,MULTIPURPOSE PASSENGER VEHICLE (MPV),Passenger,Electric,NaN,1D,...,King,WA,98107,Original Registration,In-person,5.303300e+10,1,2024,True,False
27202346,02/01/2024,VOLKSWAGEN,ID.4,2023,NaN,MULTIPURPOSE PASSENGER VEHICLE (MPV),Passenger,Electric,NaN,1D,...,Snohomish,WA,98208,Original Registration,In-person,5.306104e+10,1,2024,True,False
27202412,02/01/2024,VOLVO,XC60,2024,BLUE,MULTIPURPOSE PASSENGER VEHICLE (MPV),Passenger,Gasoline,Electric,1D,...,Clark,WA,98682,Original Registration,In-person,5.301104e+10,1,2024,False,True
27202417,02/01/2024,VOLVO,XC90,2022,NaN,MULTIPURPOSE PASSENGER VEHICLE (MPV),Passenger,Electric,Gasoline,2E,...,Thurston,WA,98501,Registration Renewal,In-person,5.306701e+10,1,2024,True,False

In [51]:
df['Make and Model'] = df['Make'] + ' ' + df['Model']

In [52]:
grouped = df.groupby(['County', 'Year'])

In [60]:
summary = grouped.agg(
    Total_Transactions=('Transaction Count', 'sum'),
    Electric_Vehicle_Count=('Is Electric', 'sum'),
    Electric_Vehicle_Ratio=('Is Electric', 'mean'),
    Second_Electric_Vehicle_Count=('Is Second Electric', 'sum'),
    Manufacturer_Distribution=('Make', lambda x: x.value_counts().to_dict()),
    Make_Model_Count=('Make and Model', 'nunique'),
    Make_Model_Distribution=('Make and Model', lambda x: x.value_counts().to_dict()),
    Vehicle_Type_Distribution=('Vehicle Type', lambda x: x.value_counts().to_dict()),
    Vehicle_Transaction_Type_Distribution=('Transaction Type', lambda x: x.value_counts().to_dict())
)

In [61]:
summary['Electric_Vehicle_Ratio'] *= 100

In [62]:
summary

             Total_Transactions  Electric_Vehicle_Count  \
County Year
Ada    2023                   1                       0
Adams  2020               19360                      19
       2021               19837                      29
       2022               19237                      36
       2023               19517                      46
...                         ...                     ...
Yakima 2020              242273                     317
       2021              246792                     474
       2022              239987                     660
       2023              241145                     982
       2024               35646                     175

             Electric_Vehicle_Ratio  Second_Electric_Vehicle_Count  \
County Year
Ada    2023                0.000000                              0
Adams  2020                0.098318                            222
       2021                0.146642                            287
       2022                0.187676                            289
       2023                0.236140                            324
...                             ...                            ...
Yakima 2020                0.131151                           2833
       2021                0.192663                           3328
       2022                0.275822                           3586
       2023                0.408297                           4121
       2024                0.492168                            678

                                     Manufacturer_Distribution  \
County Year
Ada    2023                                        {'AUDI': 1}
Adams  2020  {'CHEVROLET': 3246, 'FORD': 3179, 'HONDA': 206...
       2021  {'CHEVROLET': 3318, 'FORD': 3192, 'HONDA': 207...
       2022  {'CHEVROLET': 3178, 'FORD': 3105, 'HONDA': 206...
       2023  {'CHEVROLET': 3132, 'FORD': 3103, 'HONDA': 214...
...                                                        ...
Yakima 2020  {'FORD': 38384, 'CHEVROLET': 37011, 'TOYOTA': ...
       2021  {'FORD': 38307, 'CHEVROLET': 37316, 'TOYOTA': ...
       2022  {'FORD': 36677, 'CHEVROLET': 35608, 'TOYOTA': ...
       2023  {'FORD': 36417, 'CHEVROLET': 35158, 'TOYOTA': ...
       2024  {'FORD': 5406, 'CHEVROLET': 5200, 'TOYOTA': 40...

             Make_Model_Count  \
County Year
Ada    2023                 1
Adams  2020               918
       2021               912
       2022               911
       2023               919
...                       ...
Yakima 2020              2277
       2021              2344
       2022              2327
       2023              2303
       2024              1129

                                       Make_Model_Distribution  \
County Year
Ada    2023                                     {'AUDI S5': 1}
Adams  2020  {'FORD F-150': 930, 'CHEVROLET SILVERADO': 927...
       2021  {'CHEVROLET SILVERADO': 972, 'FORD F-150': 913...
       2022  {'CHEVROLET SILVERADO': 957, 'FORD F-150': 916...
       2023  {'CHEVROLET SILVERADO': 955, 'FORD F-150': 900...
...                                                        ...
Yakima 2020  {'FORD F-150': 9576, 'CHEVROLET SILVERADO': 93...
       2021  {'CHEVROLET SILVERADO': 9710, 'FORD F-150': 95...
       2022  {'CHEVROLET SILVERADO': 9631, 'FORD F-150': 92...
       2023  {'CHEVROLET SILVERADO': 9793, 'FORD F-150': 93...
       2024  {'CHEVROLET SILVERADO': 1503, 'FORD F-150': 13...

                                     Vehicle_Type_Distribution  \
County Year
Ada    2023                               {'PASSENGER CAR': 1}
Adams  2020  {'PASSENGER CAR': 7787, 'MULTIPURPOSE PASSENGE...
       2021  {'PASSENGER CAR': 7865, 'MULTIPURPOSE PASSENGE...
       2022  {'PASSENGER CAR': 7535, 'MULTIPURPOSE PASSENGE...
       2023  {'PASSENGER CAR': 7607, 'MULTIPURPOSE PASSENGE...
...                                                        ...
Yakima 2020  {'PASSENGER CAR': 92938, 'MULTIPURPOSE PASSENG...
       2021  {'PASSENGER CAR': 92905, 'MULTIPURPOSE PASSENG...
       2022  {'PASSENGER CAR': 88131, 'MULTIPURPOSE PASSENG...
       2023  {'PASSENGER CAR': 86680, 'MULTIPURPOSE PASSENG...
       2024  {'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 13659...

                         Vehicle_Transaction_Type_Distribution
County Year
Ada    2023            {'Registration at Time of Transfer': 1}
Adams  2020  {'Registration Renewal': 15315, 'Registration ...
       2021  {'Registration Renewal': 15295, 'Registration ...
       2022  {'Registration Renewal': 15321, 'Registration ...
       2023  {'Registration Renewal': 15500, 'Registration ...
...                                                        ...
Yakima 2020  {'Registration Renewal': 191381, 'Registration...
       2021  {'Registration Renewal': 190019, 'Registration...
       2022  {'Registration Renewal': 191721, 'Registration...
       2023  {'Registration Renewal': 195586, 'Registration...
       2024  {'Registration Renewal': 29387, 'Registration ...

[320 rows x 9 columns]

In [72]:
def get_electric_vehicle_type_distribution(x):
    electric_vehicle_mask = x['Is Electric'] | x['Is Second Electric']
    return x.loc[electric_vehicle_mask, 'Vehicle Type'].value_counts().to_dict()

In [75]:
def get_electric_vehicle_model_distribution(x):
    electric_vehicle_mask = x['Is Electric'] | x['Is Second Electric']
    return x.loc[electric_vehicle_mask, 'Make and Model'].value_counts().to_dict()

In [74]:
electric_vehicle_type_distribution = grouped.apply(get_electric_vehicle_type_distribution)

In [76]:
electric_vehicle_model_distribution = grouped.apply(get_electric_vehicle_model_distribution)

In [80]:
electric_vehicle_type_distribution

County  Year
Ada     2023                                                   {}
Adams   2020    {'PASSENGER CAR': 182, 'MULTIPURPOSE PASSENGER...
        2021    {'PASSENGER CAR': 228, 'MULTIPURPOSE PASSENGER...
        2022    {'PASSENGER CAR': 212, 'MULTIPURPOSE PASSENGER...
        2023    {'PASSENGER CAR': 223, 'MULTIPURPOSE PASSENGER...
                                      ...
Yakima  2020    {'PASSENGER CAR': 2193, 'MULTIPURPOSE PASSENGE...
        2021    {'PASSENGER CAR': 2381, 'MULTIPURPOSE PASSENGE...
        2022    {'PASSENGER CAR': 2408, 'MULTIPURPOSE PASSENGE...
        2023    {'PASSENGER CAR': 2619, 'MULTIPURPOSE PASSENGE...
        2024    {'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 403, ...
Length: 320, dtype: object

In [84]:
# merge summary and two new dataframes

final_summary = pd.merge(summary.reset_index(), electric_vehicle_type_distribution.reset_index(name='Electric_Vehicle_Type_Distribution'), on=['County', 'Year'], how='left')
final_summary = pd.merge(final_summary, electric_vehicle_model_distribution.reset_index(name='Electric_Vehicle_Model_Distribution'), on=['County', 'Year'], how='left')
final_summary

,County,Year,Total_Transactions,Electric_Vehicle_Count,Electric_Vehicle_Ratio,Second_Electric_Vehicle_Count,Manufacturer_Distribution,Make_Model_Count,Make_Model_Distribution,Vehicle_Type_Distribution,Vehicle_Transaction_Type_Distribution,Electric_Vehicle_Type_Distribution,Electric_Vehicle_Model_Distribution
0,Ada,2023,1,0,0.000000,0,{'AUDI': 1},1,{'AUDI S5': 1},{'PASSENGER CAR': 1},{'Registration at Time of Transfer': 1},{},{}
1,Adams,2020,19360,19,0.098318,222,"{'CHEVROLET': 3246, 'FORD': 3179, 'HONDA': 206...",918,"{'FORD F-150': 930, 'CHEVROLET SILVERADO': 927...","{'PASSENGER CAR': 7787, 'MULTIPURPOSE PASSENGE...","{'Registration Renewal': 15315, 'Registration ...","{'PASSENGER CAR': 182, 'MULTIPURPOSE PASSENGER...","{'TOYOTA PRIUS': 55, 'HONDA CIVIC': 28, 'TOYOT..."
2,Adams,2021,19837,29,0.146642,287,"{'CHEVROLET': 3318, 'FORD': 3192, 'HONDA': 207...",912,"{'CHEVROLET SILVERADO': 972, 'FORD F-150': 913...","{'PASSENGER CAR': 7865, 'MULTIPURPOSE PASSENGE...","{'Registration Renewal': 15295, 'Registration ...","{'PASSENGER CAR': 228, 'MULTIPURPOSE PASSENGER...","{'TOYOTA PRIUS': 65, 'HONDA CIVIC': 39, 'TOYOT..."
3,Adams,2022,19237,36,0.187676,289,"{'CHEVROLET': 3178, 'FORD': 3105, 'HONDA': 206...",911,"{'CHEVROLET SILVERADO': 957, 'FORD F-150': 916...","{'PASSENGER CAR': 7535, 'MULTIPURPOSE PASSENGE...","{'Registration Renewal': 15321, 'Registration ...","{'PASSENGER CAR': 212, 'MULTIPURPOSE PASSENGER...","{'TOYOTA PRIUS': 60, 'HONDA CIVIC': 34, 'TOYOT..."
4,Adams,2023,19517,46,0.236140,324,"{'CHEVROLET': 3132, 'FORD': 3103, 'HONDA': 214...",919,"{'CHEVROLET SILVERADO': 955, 'FORD F-150': 900...","{'PASSENGER CAR': 7607, 'MULTIPURPOSE PASSENGE...","{'Registration Renewal': 15500, 'Registration ...","{'PASSENGER CAR': 223, 'MULTIPURPOSE PASSENGER...","{'TOYOTA PRIUS': 65, 'TOYOTA RAV4': 31, 'HONDA..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,Yakima,2020,242273,317,0.131151,2833,"{'FORD': 38384, 'CHEVROLET': 37011, 'TOYOTA': ...",2277,"{'FORD F-150': 9576, 'CHEVROLET SILVERADO': 93...","{'PASSENGER CAR': 92938, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191381, 'Registration...","{'PASSENGER CAR': 2193, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 783, 'TOYOTA RAV4': 293, 'HON..."
316,Yakima,2021,246792,474,0.192663,3328,"{'FORD': 38307, 'CHEVROLET': 37316, 'TOYOTA': ...",2344,"{'CHEVROLET SILVERADO': 9710, 'FORD F-150': 95...","{'PASSENGER CAR': 92905, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 190019, 'Registration...","{'PASSENGER CAR': 2381, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 759, 'TOYOTA RAV4': 410, 'TOY..."
317,Yakima,2022,239987,660,0.275822,3586,"{'FORD': 36677, 'CHEVROLET': 35608, 'TOYOTA': ...",2327,"{'CHEVROLET SILVERADO': 9631, 'FORD F-150': 92...","{'PASSENGER CAR': 88131, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191721, 'Registration...","{'PASSENGER CAR': 2408, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 746, 'TOYOTA RAV4': 495, 'TOY..."
318,Yakima,2023,241145,982,0.408297,4121,"{'FORD': 36417, 'CHEVROLET': 35158, 'TOYOTA': ...",2303,"{'CHEVROLET SILVERADO': 9793, 'FORD F-150': 93...","{'PASSENGER CAR': 86680, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 195586, 'Registration...","{'PASSENGER CAR': 2619, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 739, 'TOYOTA RAV4': 608, 'TOY..."
319,Yakima,2024,35646,175,0.492168,678,"{'FORD': 5406, 'CHEVROLET': 5200, 'TOYOTA': 40...",1129,"{'CHEVROLET SILVERADO': 1503, 'FORD F-150': 13...",{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 13659...,"{'Registration Renewal': 29387, 'Registration ...","{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 403, ...","{'TOYOTA PRIUS': 110, 'TOYOTA RAV4': 94, 'TOYO..."

### Fill missing year

In [102]:

len(final_summary['County'].unique())

99

In [105]:
len(df['County'].unique())

99

In [107]:
counties = final_summary['County'].unique()
years = [2020, 2021, 2022, 2023, 2024]

In [110]:
all_combinations = pd.MultiIndex.from_product([counties, years], names=['County', 'Year'])
all_combinations_df = pd.DataFrame(index=all_combinations).reset_index()
all_combinations_df

     County  Year
0       Ada  2020
1       Ada  2021
2       Ada  2022
3       Ada  2023
4       Ada  2024
..      ...   ...
490  Yakima  2020
491  Yakima  2021
492  Yakima  2022
493  Yakima  2023
494  Yakima  2024

[495 rows x 2 columns]

In [111]:
final_summary_full = pd.merge(all_combinations_df, final_summary, on=['County', 'Year'], how='left')
final_summary_full

,County,Year,Total_Transactions,Electric_Vehicle_Count,Electric_Vehicle_Ratio,Second_Electric_Vehicle_Count,Manufacturer_Distribution,Make_Model_Count,Make_Model_Distribution,Vehicle_Type_Distribution,Vehicle_Transaction_Type_Distribution,Electric_Vehicle_Type_Distribution,Electric_Vehicle_Model_Distribution
0,Ada,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ada,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ada,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ada,2023,1.0,0.0,0.000000,0.0,{'AUDI': 1},1.0,{'AUDI S5': 1},{'PASSENGER CAR': 1},{'Registration at Time of Transfer': 1},{},{}
4,Ada,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,Yakima,2020,242273.0,317.0,0.131151,2833.0,"{'FORD': 38384, 'CHEVROLET': 37011, 'TOYOTA': ...",2277.0,"{'FORD F-150': 9576, 'CHEVROLET SILVERADO': 93...","{'PASSENGER CAR': 92938, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191381, 'Registration...","{'PASSENGER CAR': 2193, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 783, 'TOYOTA RAV4': 293, 'HON..."
491,Yakima,2021,246792.0,474.0,0.192663,3328.0,"{'FORD': 38307, 'CHEVROLET': 37316, 'TOYOTA': ...",2344.0,"{'CHEVROLET SILVERADO': 9710, 'FORD F-150': 95...","{'PASSENGER CAR': 92905, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 190019, 'Registration...","{'PASSENGER CAR': 2381, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 759, 'TOYOTA RAV4': 410, 'TOY..."
492,Yakima,2022,239987.0,660.0,0.275822,3586.0,"{'FORD': 36677, 'CHEVROLET': 35608, 'TOYOTA': ...",2327.0,"{'CHEVROLET SILVERADO': 9631, 'FORD F-150': 92...","{'PASSENGER CAR': 88131, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191721, 'Registration...","{'PASSENGER CAR': 2408, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 746, 'TOYOTA RAV4': 495, 'TOY..."
493,Yakima,2023,241145.0,982.0,0.408297,4121.0,"{'FORD': 36417, 'CHEVROLET': 35158, 'TOYOTA': ...",2303.0,"{'CHEVROLET SILVERADO': 9793, 'FORD F-150': 93...","{'PASSENGER CAR': 86680, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 195586, 'Registration...","{'PASSENGER CAR': 2619, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 739, 'TOYOTA RAV4': 608, 'TOY..."
494,Yakima,2024,35646.0,175.0,0.492168,678.0,"{'FORD': 5406, 'CHEVROLET': 5200, 'TOYOTA': 40...",1129.0,"{'CHEVROLET SILVERADO': 1503, 'FORD F-150': 13...",{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 13659...,"{'Registration Renewal': 29387, 'Registration ...","{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 403, ...","{'TOYOTA PRIUS': 110, 'TOYOTA RAV4': 94, 'TOYO..."

In [ ]:
final_summary_full['Total_Transactions'] = final_summary_full['Total_Transactions'].fillna(0)

In [118]:
final_summary_full.fillna({'Total_Transactions': 0, 
                           'Electric_Vehicle_Count': 0, 
                           'Electric_Vehicle_Ratio': 0, 
                           'Second_Electric_Vehicle_Count': 0, 
                           'Make_Model_Count': 0, 
                           }, inplace=True)

In [119]:
dictionary_columns = ['Manufacturer_Distribution', 'Make_Model_Distribution', 'Vehicle_Type_Distribution', 
                      'Vehicle_Transaction_Type_Distribution', 'Electric_Vehicle_Type_Distribution', 'Electric_Vehicle_Model_Distribution']
for column in dictionary_columns:
    final_summary_full[column].fillna({i: {} for i in final_summary_full.index}, inplace=True)

In [120]:
final_summary_full

,County,Year,Total_Transactions,Electric_Vehicle_Count,Electric_Vehicle_Ratio,Second_Electric_Vehicle_Count,Manufacturer_Distribution,Make_Model_Count,Make_Model_Distribution,Vehicle_Type_Distribution,Vehicle_Transaction_Type_Distribution,Electric_Vehicle_Type_Distribution,Electric_Vehicle_Model_Distribution
0,Ada,2020,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{}
1,Ada,2021,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{}
2,Ada,2022,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{}
3,Ada,2023,1.0,0.0,0.000000,0.0,{'AUDI': 1},1.0,{'AUDI S5': 1},{'PASSENGER CAR': 1},{'Registration at Time of Transfer': 1},{},{}
4,Ada,2024,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,Yakima,2020,242273.0,317.0,0.131151,2833.0,"{'FORD': 38384, 'CHEVROLET': 37011, 'TOYOTA': ...",2277.0,"{'FORD F-150': 9576, 'CHEVROLET SILVERADO': 93...","{'PASSENGER CAR': 92938, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191381, 'Registration...","{'PASSENGER CAR': 2193, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 783, 'TOYOTA RAV4': 293, 'HON..."
491,Yakima,2021,246792.0,474.0,0.192663,3328.0,"{'FORD': 38307, 'CHEVROLET': 37316, 'TOYOTA': ...",2344.0,"{'CHEVROLET SILVERADO': 9710, 'FORD F-150': 95...","{'PASSENGER CAR': 92905, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 190019, 'Registration...","{'PASSENGER CAR': 2381, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 759, 'TOYOTA RAV4': 410, 'TOY..."
492,Yakima,2022,239987.0,660.0,0.275822,3586.0,"{'FORD': 36677, 'CHEVROLET': 35608, 'TOYOTA': ...",2327.0,"{'CHEVROLET SILVERADO': 9631, 'FORD F-150': 92...","{'PASSENGER CAR': 88131, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191721, 'Registration...","{'PASSENGER CAR': 2408, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 746, 'TOYOTA RAV4': 495, 'TOY..."
493,Yakima,2023,241145.0,982.0,0.408297,4121.0,"{'FORD': 36417, 'CHEVROLET': 35158, 'TOYOTA': ...",2303.0,"{'CHEVROLET SILVERADO': 9793, 'FORD F-150': 93...","{'PASSENGER CAR': 86680, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 195586, 'Registration...","{'PASSENGER CAR': 2619, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 739, 'TOYOTA RAV4': 608, 'TOY..."
494,Yakima,2024,35646.0,175.0,0.492168,678.0,"{'FORD': 5406, 'CHEVROLET': 5200, 'TOYOTA': 40...",1129.0,"{'CHEVROLET SILVERADO': 1503, 'FORD F-150': 13...",{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 13659...,"{'Registration Renewal': 29387, 'Registration ...","{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 403, ...","{'TOYOTA PRIUS': 110, 'TOYOTA RAV4': 94, 'TOYO..."

In [121]:
df2 = pd.read_csv("../data/Data_Cleaned.csv")

In [122]:
df2['Make and Model'] = df2['Make'] + ' ' + df2['Model']

In [123]:
aggregate_df2 = df2.groupby(['County']).aggregate(
    Manufacturer_Distribution_2023=('Make', lambda x: x.value_counts().to_dict()),
    Make_Model_Distribution_2023=('Make and Model', lambda x: x.value_counts().to_dict()),
    Eletric_Vehicle_Type_2023=('Electric Vehicle Type', lambda x: x.value_counts().to_dict())
    )

aggregate_df2

,Manufacturer_Distribution_2023,Make_Model_Distribution_2023,Eletric_Vehicle_Type_2023
County,,,
Adams,"{'TESLA': 21, 'FORD': 8, 'CHEVROLET': 5, 'KIA'...","{'TESLA MODEL 3': 9, 'TESLA MODEL Y': 7, 'FORD...","{'Battery Electric Vehicle (BEV)': 35, 'Plug-i..."
Asotin,"{'TESLA': 17, 'TOYOTA': 13, 'CHEVROLET': 10, '...","{'TESLA MODEL 3': 7, 'JEEP WRANGLER': 6, 'TOYO...","{'Battery Electric Vehicle (BEV)': 47, 'Plug-i..."
Benton,"{'TESLA': 878, 'CHEVROLET': 251, 'FORD': 159, ...","{'TESLA MODEL 3': 382, 'TESLA MODEL Y': 325, '...","{'Battery Electric Vehicle (BEV)': 1490, 'Plug..."
Chelan,"{'TESLA': 456, 'NISSAN': 112, 'CHEVROLET': 103...","{'TESLA MODEL Y': 214, 'TESLA MODEL 3': 135, '...","{'Battery Electric Vehicle (BEV)': 825, 'Plug-..."
Clallam,"{'TESLA': 287, 'CHEVROLET': 165, 'NISSAN': 129...","{'TESLA MODEL 3': 122, 'NISSAN LEAF': 118, 'TE...","{'Battery Electric Vehicle (BEV)': 726, 'Plug-..."
Clark,"{'TESLA': 4305, 'CHEVROLET': 866, 'NISSAN': 82...","{'TESLA MODEL Y': 1814, 'TESLA MODEL 3': 1708,...","{'Battery Electric Vehicle (BEV)': 7689, 'Plug..."
Columbia,"{'TESLA': 5, 'FORD': 5, 'CHEVROLET': 4, 'NISSA...","{'CHEVROLET BOLT EV': 4, 'FORD F-150': 4, 'TES...",{'Battery Electric Vehicle (BEV)': 16}
Cowlitz,"{'TESLA': 340, 'CHEVROLET': 106, 'FORD': 71, '...","{'TESLA MODEL 3': 142, 'TESLA MODEL Y': 124, '...","{'Battery Electric Vehicle (BEV)': 635, 'Plug-..."
Douglas,"{'TESLA': 155, 'NISSAN': 41, 'FORD': 37, 'CHEV...","{'TESLA MODEL Y': 68, 'TESLA MODEL 3': 52, 'NI...","{'Battery Electric Vehicle (BEV)': 277, 'Plug-..."
Ferry,"{'TESLA': 19, 'TOYOTA': 4, 'CHEVROLET': 3, 'NI...","{'TESLA MODEL 3': 8, 'TESLA MODEL Y': 6, 'TESL...","{'Battery Electric Vehicle (BEV)': 27, 'Plug-i..."
Franklin,"{'TESLA': 270, 'CHEVROLET': 68, 'FORD': 46, 'N...","{'TESLA MODEL 3': 131, 'TESLA MODEL Y': 94, 'N...","{'Battery Electric Vehicle (BEV)': 413, 'Plug-..."
Garfield,"{'FORD': 2, 'TOYOTA': 1}","{'FORD C-MAX': 2, 'TOYOTA RAV4 PRIME': 1}",{'Plug-in Hybrid Electric Vehicle (PHEV)': 3}
Grant,"{'TESLA': 244, 'CHEVROLET': 61, 'FORD': 55, 'J...","{'TESLA MODEL 3': 100, 'TESLA MODEL Y': 95, 'T...","{'Battery Electric Vehicle (BEV)': 399, 'Plug-..."
Grays Harbor,"{'TESLA': 191, 'CHEVROLET': 96, 'FORD': 84, 'T...","{'TESLA MODEL 3': 89, 'TESLA MODEL Y': 69, 'CH...","{'Battery Electric Vehicle (BEV)': 411, 'Plug-..."
Island,"{'TESLA': 666, 'CHEVROLET': 234, 'NISSAN': 158...","{'TESLA MODEL Y': 272, 'TESLA MODEL 3': 251, '...","{'Battery Electric Vehicle (BEV)': 1390, 'Plug..."
Jefferson,"{'TESLA': 231, 'NISSAN': 164, 'CHEVROLET': 163...","{'NISSAN LEAF': 162, 'TESLA MODEL Y': 96, 'CHE...","{'Battery Electric Vehicle (BEV)': 696, 'Plug-..."
King,"{'TESLA': 44894, 'NISSAN': 6760, 'CHEVROLET': ...","{'TESLA MODEL Y': 20447, 'TESLA MODEL 3': 1682...","{'Battery Electric Vehicle (BEV)': 74942, 'Plu..."
Kitsap,"{'TESLA': 1927, 'NISSAN': 630, 'CHEVROLET': 58...","{'TESLA MODEL Y': 799, 'TESLA MODEL 3': 771, '...","{'Battery Electric Vehicle (BEV)': 4306, 'Plug..."
Kittitas,"{'TESLA': 297, 'CHEVROLET': 54, 'FORD': 39, 'R...","{'TESLA MODEL Y': 121, 'TESLA MODEL 3': 110, '...","{'Battery Electric Vehicle (BEV)': 500, 'Plug-..."
Klickitat,"{'TESLA': 97, 'CHEVROLET': 45, 'TOYOTA': 26, '...","{'TESLA MODEL Y': 55, 'CHEVROLET BOLT EV': 31,...","{'Battery Electric Vehicle (BEV)': 209, 'Plug-..."
Lewis,"{'TESLA': 208, 'CHEVROLET': 91, 'CHRYSLER': 83...","{'TESLA MODEL 3': 95, 'CHRYSLER PACIFICA': 83,...","{'Battery Electric Vehicle (BEV)': 420, 'Plug-..."
Lincoln,"{'CHEVROLET': 12, 'TESLA': 11, 'BMW': 5, 'FORD...","{'CHEVROLET BOLT EV': 6, 'CHEVROLET VOLT': 6, ...","{'Plug-in Hybrid Electric Vehicle (PHEV)': 25,..."
Mason,"{'TESLA': 301, 'CHEVROLET': 108, 'FORD': 70, '...","{'TESLA MODEL 3': 129, 'TESLA MODEL Y': 102, '...","{'Battery Electric Vehicle (BEV)': 587, 'Plug-..."
Okanogan,"{'TESLA': 88, 'CHEVROLET': 33, 'TOYOTA': 23, '...","{'TESLA MODEL Y': 52, 'TESLA MODEL 3': 25, 'CH...","{'Battery Electric Vehicle (BEV)': 182, 'Plug-..."
Pacific,"{'TESLA': 51, 'TOYOTA': 36, 'CHEVROLET': 28, '...","{'TESLA MODEL 3': 25, 'TESLA MODEL Y': 20, 'TO...","{'Battery Electric Vehicle (BEV)': 106, 'Plug-..."
Pend Oreille,"{'TESLA': 18, 'FORD': 7, 'NISSAN': 5, 'JEEP': ...","{'TESLA MODEL Y': 8, 'TESLA MODEL 3': 7, 'JEEP...","{'Battery Electric Vehicle (BEV)': 34, 'Plug-i..."
Pierce,"{'TESLA': 5772, 'CHEVROLET': 1118, 'NISSAN': 1...","{'TESLA MODEL Y': 2433, 'TESLA MODEL 3': 2362,...","{'Battery Electric Vehicle (BEV)': 10484, 'Plu..."
San Juan,"{'TESLA': 209, 'NISSAN': 204, 'CHEVROLET': 125...","{'NISSAN LEAF': 202, 'TESLA MODEL Y': 86, 'CHE...","{'Battery Electric Vehicle (BEV)': 737, 'Plug-..."
Skagit,"{'TESLA': 669, 'CHEVROLET': 240, 'NISSAN': 170...","{'TESLA MODEL Y': 289, 'TESLA MODEL 3': 238, '...","{'Battery Electric Vehicle (BEV)': 1425, 'Plug..."
Skamania,"{'TESLA': 73, 'CHEVROLET': 22, 'TOYOTA': 16, '...","{'TESLA MODEL 3': 32, 'TESLA MODEL Y': 25, 'CH...","{'Battery Electric Vehicle (BEV)': 138, 'Plug-..."
Snohomish,"{'TESLA': 10918, 'NISSAN': 1627, 'CHEVROLET': ...","{'TESLA MODEL Y': 5589, 'TESLA MODEL 3': 3841,...","{'Battery Electric Vehicle (BEV)': 17294, 'Plu..."
Spokane,"{'TESLA': 1725, 'CHEVROLET': 420, 'FORD': 342,...","{'TESLA MODEL Y': 790, 'TESLA MODEL 3': 607, '...","{'Battery Electric Vehicle (BEV)': 3134, 'Plug..."
Stevens,"{'TESLA': 84, 'CHEVROLET': 39, 'TOYOTA': 15, '...","{'TESLA MODEL Y': 39, 'TESLA MODEL 3': 31, 'CH...","{'Battery Electric Vehicle (BEV)': 149, 'Plug-..."
Thurston,"{'TESLA': 2035, 'CHEVROLET': 948, 'FORD': 633,...","{'TESLA MODEL Y': 863, 'TESLA MODEL 3': 812, '...","{'Battery Electric Vehicle (BEV)': 4791, 'Plug..."
Wahkiakum,"{'TESLA': 18, 'CHEVROLET': 10, 'FORD': 8, 'TOY...","{'CHEVROLET BOLT EV': 7, 'TESLA MODEL 3': 7, '...","{'Battery Electric Vehicle (BEV)': 38, 'Plug-i..."
Walla Walla,"{'TESLA': 146, 'CHEVROLET': 51, 'FORD': 38, 'T...","{'TESLA MODEL Y': 60, 'TESLA MODEL 3': 58, 'NI...","{'Battery Electric Vehicle (BEV)': 294, 'Plug-..."
Whatcom,"{'TESLA': 1291, 'NISSAN': 634, 'CHEVROLET': 46...","{'NISSAN LEAF': 611, 'TESLA MODEL Y': 550, 'TE...","{'Battery Electric Vehicle (BEV)': 3169, 'Plug..."
Whitman,"{'TESLA': 118, 'CHEVROLET': 53, 'FORD': 35, 'T...","{'TESLA MODEL Y': 58, 'TESLA MODEL 3': 47, 'CH...","{'Battery Electric Vehicle (BEV)': 220, 'Plug-..."
Yakima,"{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."

In [124]:
final_summary_with_2023 = pd.merge(final_summary_full, aggregate_df2, on='County', how='left')
final_summary_with_2023

,County,Year,Total_Transactions,Electric_Vehicle_Count,Electric_Vehicle_Ratio,Second_Electric_Vehicle_Count,Manufacturer_Distribution,Make_Model_Count,Make_Model_Distribution,Vehicle_Type_Distribution,Vehicle_Transaction_Type_Distribution,Electric_Vehicle_Type_Distribution,Electric_Vehicle_Model_Distribution,Manufacturer_Distribution_2023,Make_Model_Distribution_2023,Eletric_Vehicle_Type_2023
0,Ada,2020,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{},NaN,NaN,NaN
1,Ada,2021,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{},NaN,NaN,NaN
2,Ada,2022,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{},NaN,NaN,NaN
3,Ada,2023,1.0,0.0,0.000000,0.0,{'AUDI': 1},1.0,{'AUDI S5': 1},{'PASSENGER CAR': 1},{'Registration at Time of Transfer': 1},{},{},NaN,NaN,NaN
4,Ada,2024,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{},NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,Yakima,2020,242273.0,317.0,0.131151,2833.0,"{'FORD': 38384, 'CHEVROLET': 37011, 'TOYOTA': ...",2277.0,"{'FORD F-150': 9576, 'CHEVROLET SILVERADO': 93...","{'PASSENGER CAR': 92938, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191381, 'Registration...","{'PASSENGER CAR': 2193, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 783, 'TOYOTA RAV4': 293, 'HON...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."
491,Yakima,2021,246792.0,474.0,0.192663,3328.0,"{'FORD': 38307, 'CHEVROLET': 37316, 'TOYOTA': ...",2344.0,"{'CHEVROLET SILVERADO': 9710, 'FORD F-150': 95...","{'PASSENGER CAR': 92905, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 190019, 'Registration...","{'PASSENGER CAR': 2381, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 759, 'TOYOTA RAV4': 410, 'TOY...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."
492,Yakima,2022,239987.0,660.0,0.275822,3586.0,"{'FORD': 36677, 'CHEVROLET': 35608, 'TOYOTA': ...",2327.0,"{'CHEVROLET SILVERADO': 9631, 'FORD F-150': 92...","{'PASSENGER CAR': 88131, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191721, 'Registration...","{'PASSENGER CAR': 2408, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 746, 'TOYOTA RAV4': 495, 'TOY...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."
493,Yakima,2023,241145.0,982.0,0.408297,4121.0,"{'FORD': 36417, 'CHEVROLET': 35158, 'TOYOTA': ...",2303.0,"{'CHEVROLET SILVERADO': 9793, 'FORD F-150': 93...","{'PASSENGER CAR': 86680, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 195586, 'Registration...","{'PASSENGER CAR': 2619, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 739, 'TOYOTA RAV4': 608, 'TOY...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."
494,Yakima,2024,35646.0,175.0,0.492168,678.0,"{'FORD': 5406, 'CHEVROLET': 5200, 'TOYOTA': 40...",1129.0,"{'CHEVROLET SILVERADO': 1503, 'FORD F-150': 13...",{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 13659...,"{'Registration Renewal': 29387, 'Registration ...","{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 403, ...","{'TOYOTA PRIUS': 110, 'TOYOTA RAV4': 94, 'TOYO...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."

In [125]:
dictionary_columns = ['Manufacturer_Distribution_2023', 'Make_Model_Distribution_2023', 'Eletric_Vehicle_Type_2023']
for column in dictionary_columns:
    final_summary_with_2023[column].fillna({i: {} for i in final_summary_with_2023.index}, inplace=True)

In [127]:
final_summary_with_2023

,County,Year,Total_Transactions,Electric_Vehicle_Count,Electric_Vehicle_Ratio,Second_Electric_Vehicle_Count,Manufacturer_Distribution,Make_Model_Count,Make_Model_Distribution,Vehicle_Type_Distribution,Vehicle_Transaction_Type_Distribution,Electric_Vehicle_Type_Distribution,Electric_Vehicle_Model_Distribution,Manufacturer_Distribution_2023,Make_Model_Distribution_2023,Eletric_Vehicle_Type_2023
0,Ada,2020,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{},{},{},{}
1,Ada,2021,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{},{},{},{}
2,Ada,2022,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{},{},{},{}
3,Ada,2023,1.0,0.0,0.000000,0.0,{'AUDI': 1},1.0,{'AUDI S5': 1},{'PASSENGER CAR': 1},{'Registration at Time of Transfer': 1},{},{},{},{},{}
4,Ada,2024,0.0,0.0,0.000000,0.0,{},0.0,{},{},{},{},{},{},{},{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,Yakima,2020,242273.0,317.0,0.131151,2833.0,"{'FORD': 38384, 'CHEVROLET': 37011, 'TOYOTA': ...",2277.0,"{'FORD F-150': 9576, 'CHEVROLET SILVERADO': 93...","{'PASSENGER CAR': 92938, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191381, 'Registration...","{'PASSENGER CAR': 2193, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 783, 'TOYOTA RAV4': 293, 'HON...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."
491,Yakima,2021,246792.0,474.0,0.192663,3328.0,"{'FORD': 38307, 'CHEVROLET': 37316, 'TOYOTA': ...",2344.0,"{'CHEVROLET SILVERADO': 9710, 'FORD F-150': 95...","{'PASSENGER CAR': 92905, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 190019, 'Registration...","{'PASSENGER CAR': 2381, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 759, 'TOYOTA RAV4': 410, 'TOY...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."
492,Yakima,2022,239987.0,660.0,0.275822,3586.0,"{'FORD': 36677, 'CHEVROLET': 35608, 'TOYOTA': ...",2327.0,"{'CHEVROLET SILVERADO': 9631, 'FORD F-150': 92...","{'PASSENGER CAR': 88131, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 191721, 'Registration...","{'PASSENGER CAR': 2408, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 746, 'TOYOTA RAV4': 495, 'TOY...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."
493,Yakima,2023,241145.0,982.0,0.408297,4121.0,"{'FORD': 36417, 'CHEVROLET': 35158, 'TOYOTA': ...",2303.0,"{'CHEVROLET SILVERADO': 9793, 'FORD F-150': 93...","{'PASSENGER CAR': 86680, 'MULTIPURPOSE PASSENG...","{'Registration Renewal': 195586, 'Registration...","{'PASSENGER CAR': 2619, 'MULTIPURPOSE PASSENGE...","{'TOYOTA PRIUS': 739, 'TOYOTA RAV4': 608, 'TOY...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."
494,Yakima,2024,35646.0,175.0,0.492168,678.0,"{'FORD': 5406, 'CHEVROLET': 5200, 'TOYOTA': 40...",1129.0,"{'CHEVROLET SILVERADO': 1503, 'FORD F-150': 13...",{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 13659...,"{'Registration Renewal': 29387, 'Registration ...","{'MULTIPURPOSE PASSENGER VEHICLE (MPV)': 403, ...","{'TOYOTA PRIUS': 110, 'TOYOTA RAV4': 94, 'TOYO...","{'TESLA': 436, 'CHEVROLET': 99, 'TOYOTA': 62, ...","{'TESLA MODEL 3': 190, 'TESLA MODEL Y': 158, '...","{'Battery Electric Vehicle (BEV)': 688, 'Plug-..."

In [128]:
final_summary_with_2023.to_csv("../data/aggregated_data.csv", index=False)